### ISSUE TITLE
Improve HeatMap Color Range to Taxonomy

### ISSUE THREAD

**Issue by Nilad** [moshi4/ANIclustermap#1]
Hi,

Is it possible to have a special range color for taxonomist user or the possibility to define (by a configuration file) a range by color ?

For the taxonomist user, they like to have a color range of 100% ANI, 99%-95%, 94%-83%, 82%-70% and 70%-0%.

Thanks for your work.

Have a good day.

**Comment by moshi4** [comment]
Hi, @Nilad

Thank you for your suggestions for functionality improvements.
I am glad that this is my first issue for my OSS.

I thought the feature you mentioned was useful, so I implemented it in the new v1.1.0 version.
It is designed to allow specifying color range values via command option `--cmap_ranges`.

ANIclustermap v1.1.0 is already available in `pip install`.
It will take about 1 to 2 days to be available from `conda install`.

**Example1**

Test dataset = [small_dataset](https://github.com/moshi4/ANIclustermap/wiki/dataset/small_dataset.zip) (Click link to download)
```shell
ANIclustermap -i ./small_dataset -o ./cmap_ranges_example1 --fig_width 15 --annotation \
              --cmap_ranges 70,82,95,100,100
```
![ANIclustermap](https://user-images.githubusercontent.com/41852815/165491966-fe4e8c2c-43bf-429a-a838-ede942d92666.png)

**Example2**

```shell
ANIclustermap -i ./small_dataset -o ./cmap_ranges_example2 --fig_width 15 --annotation \
              --cmap_ranges 80,85,90,95,100 --cmap_colors cyan,blue
```
![ANIclustermap](https://user-images.githubusercontent.com/41852815/165492488-52cd994d-d3c1-419f-ad44-ee5a5e072335.png)
