### ISSUE TITLE
[Question] Visulize existing fastANI output 

### ISSUE THREAD

**Issue by renrok** [moshi4/ANIclustermap#12]
Hey, I came accross you piece when looking for a way to visulize the fastANI output. So I was wondering if it is possible to input an existing fastANI output into your ANIclustermap. 

All the best, 
Lisa

**Comment by moshi4** [comment]
Hi @renrok,

Unfortunately, ANIclustermap does not have the functionality to visualize from existing user-created FastANI output results.
