### ISSUE TITLE
Only first row annotation is shown on clustermap

### ISSUE THREAD

**Issue by lingvv** [moshi4/ANIclustermap#13]
Thank you for providing this incredible tool! 
However, I’ve encountered an issue with the output and its annotations. 
According to the tutorial, the expected output should look like this:
![image](https://github.com/moshi4/ANIclustermap/assets/148859014/c570dd9f-d707-44ff-ae89-bdff17ce6647)

However, when I reproduced the same dataset and used the same code, the actual output I obtained was as follows:
![ANIclustermap](https://github.com/moshi4/ANIclustermap/assets/148859014/157929e4-c6b5-4e6f-b444-f07c3263f769)

Code:
`ANIclustermap -i normal_dataset/normal_dataset/ -o ANIclustermap_result --fig_width 20 --fig_height 15 --annotation`

Thank you for your help!

**Comment by moshi4** [comment]
You are probably having problems with an older version of seaborn or matplotlib in your environment. Please do a clean install and re-run ANIclustermap in your new virtual environment. Close issue as it is not a problem with ANIclustermap itself.

Reference: 
https://stackoverflow.com/questions/77165100/only-the-first-row-of-annotations-displayed-on-seaborn-heatmap

**Comment by lingvv** [comment]
Good day, @moshi4 

Thank you for your prompt response regarding my issue. 
I’ve resolved the error, which was indeed caused by the Seaborn software version, as you mentioned. 

For anyone encountering a similar issue, you can:
check the version by running `pip show seaborn `
and 
upgrade Seaborn using `pip install seaborn --upgrade`
