### ISSUE TITLE
ANIclustermap.png shows only two colors when genomes are very similar (ANI>99.9)

### ISSUE THREAD

**Issue by d4straub** [moshi4/ANIclustermap#14]
Thanks for the great tool, it make comparing genomes so easy!

ANIclustermap.png/svg shows only two colors (red & green) when genomes are very similar (ANI>99.9). This might be caused by the truncation to (only) one digit after the decimal point. The legend has two decimal digits, but the numbers in the cells only one. Unfortunately that renders the figure useless. I also tested with `--cmap_ranges 99.93,99.94,99.95,99.96,99.97,99.98,99.99,100`, but no change. I attached hopefully relevant files.
![ANIclustermap](https://github.com/moshi4/ANIclustermap/assets/42973691/3fdcb9bc-9132-4825-b9b3-c29ff6e136a6)
[ANIclustermap_matrix.tsv.txt](https://github.com/user-attachments/files/16067171/ANIclustermap_matrix.tsv.txt)

I would hope for either being able to choose the number of digit after the decimal point or use a default of 2. In my opinion, the truncation of the digits after the decimal point should be only for displaying but not affect the color scale, this part I would even consider a bug.

**Comment by moshi4** [comment]
Hi @d4straub, 

Thanks for reporting issue. Fixed in [v1.4.0](https://github.com/moshi4/ANIclustermap/releases/tag/v1.4.0) release.

___

Figure with `--annotation --annotation_fmt .5g` option

![ANIclustermap](https://github.com/user-attachments/assets/6d92f1c3-7ef6-47cd-94c9-c897b4df9056)
