### ISSUE TITLE
Input file - similarity matrix

### ISSUE THREAD

**Issue by Nilad** [moshi4/ANIclustermap#2]
Hi,

Second issue to enhance this tools =)

Most People use differents tools for ANI score like OrthoANI or want to use AAI score or mash distance values, all theses tools produce a similarity matrix file.

Is it possible to bypass the FastANI step in your tool by directly passing the similarity matrix (**tsv**/csv format) ?

Thanks in advance for your work.

Have a good day.

**Comment by moshi4** [comment]
I think it would be a somewhat tedious task to make it possible to process similarity matrix result files in a generic way, as they differ slightly from software to software.
If I personally have the opportunity to use other ANI or AAI calculation software, I may consider adding a method to create a clustermap based on the output of other software.

For now, please let me hold off on this issue.
