### ISSUE TITLE
ERROR: Number of input genome fasta file is less than 1.

### ISSUE THREAD

**Issue by H440775h** [moshi4/ANIclustermap#3]
received the above error even when use example data

**Comment by moshi4** [comment]
> ERROR: Number of input genome fasta file is less than 1.

This error occurs under the following conditions

- Input directory does not exist
- Genomic FASTA files with `*.fa|*.fna[.gz]|*.fasta` extension do not exist in the input directory

Can you please check if the input directory (specified by `-i|--indir` option) is set correctly?

If the error still occurs after confirming that the input directory is set correctly, please provide data/commands that can reproduce the error. I will investigate the cause of the error.

**Comment by H440775h** [comment]
Thanks its works now
