### ISSUE TITLE
Not loading my genome

### ISSUE THREAD

**Issue by vebaev** [moshi4/ANIclustermap#5]
Dear all,
I have downloaded some strain assemblies (looking like files GCF_000014505.1_ASM1450v1_genomic.fna)
In the folder I have put my strain assembly fna file, but whatever name I give to my file it is not present in the png, and I see that workflow loads all files but mine (and I checked the fasta is fine)? Can you help?

**Comment by moshi4** [comment]
Hi, @vebaev

Please check the following two points

- **Is your genome fasta file extension a valid one?**
  Only `*.fa`, `*.fna`, `*.fna.gz`, `*.fasta` extensions are valid for loading.

- **After running ANIclustermap once, have you added the fasta file and re-run it with the same command as the first time?**
  ANIclustermap is designed to reuse previous fastANI results. Therefore, the newly added fasta file may be ignored. Try changing the output directory (`-o` option) and it may work as expected.

**Comment by vebaev** [comment]
Hi,
Yes the fasta is *.fna
indeed first I forgot to add it and made a run. After that I add it, i tried with making new input dir, new output dir, ranaming the file, nothing works its ignored?

**Comment by moshi4** [comment]
Hmmm, I'm not sure what caused this.

If you could upload all the data in your input directory here, I could see the cause right away, but it's hard to upload research data, isn't it?

Can you upload (or paste) the following data?
- List of file names in the input directory (e.g. `ls -l [Input Directory]`)
- `work/genome_fasta_file_list.txt` file in output directory

**Comment by vebaev** [comment]
I did a new folder strains2, where the files are 24:
`GCF_000014505.1_ASM1450v1_genomic.fna
GCF_000496265.1_ASM49626v1_genomic.fna
GCF_001411765.2_ASM141176v2_genomic.fna
GCF_002202155.1_ASM220215v1_genomic.fna
GCF_002982155.1_ASM298215v1_genomic.fna
GCF_003429405.1_ASM342940v1_genomic.fna
GCF_006770865.1_ASM677086v1_genomic.fna
GCF_007923185.1_ASM792318v1_genomic.fna
GCF_009791435.1_ASM979143v1_genomic.fna
GCF_009913955.1_ASM991395v1_genomic.fna
GCF_009913995.1_ASM991399v1_genomic.fna
GCF_009914015.1_ASM991401v1_genomic.fna
GCF_009914035.1_ASM991403v1_genomic.fna
GCF_009930955.1_ASM993095v1_genomic.fna
GCF_016028695.1_ASM1602869v1_genomic.fna
GCF_016126975.1_ASM1612697v1_genomic.fna
GCF_016127775.1_ASM1612777v1_genomic.fna
GCF_016128215.1_ASM1612821v1_genomic.fna
GCF_016726885.1_ASM1672688v1_genomic.fna
GCF_019614475.1_ASM1961447v1_genomic.fna
GCF_023277765.1_ASM2327776v1_genomic.fna
GCF_023277785.1_ASM2327778v1_genomic.fna
GCF_023277805.1_ASM2327780v1_genomic.fna
P_pentosaceus_genomic.fna `

The program output is:
```
`ANIclustermap -i strains2 -o output --fig_width 20 --fig_height 16 --annotation --cmap_colors white,orange,red
 Step1: Run fastANI between all-vs-all 23 genomes.
```

```
Reference = [strains2/GCF_023277765.1_ASM2327776v1_genomic.fna, strains2/GCF_023277785.1_ASM2327778v1_genomic.fna, strains2/GCF_000014505.1_ASM1450v1_genomic.fna, strains2/GCF_009791435.1_ASM979143v1_genomic.fna, strains2/GCF_009930955.1_ASM993095v1_genomic.fna, strains2/GCF_009913995.1_ASM991399v1_genomic.fna, strains2/GCF_002982155.1_ASM298215v1_genomic.fna, strains2/GCF_009914035.1_ASM991403v1_genomic.fna, strains2/GCF_000496265.1_ASM49626v1_genomic.fna, strains2/GCF_009914015.1_ASM991401v1_genomic.fna, strains2/GCF_002202155.1_ASM220215v1_genomic.fna, strains2/GCF_006770865.1_ASM677086v1_genomic.fna, strains2/GCF_007923185.1_ASM792318v1_genomic.fna, strains2/GCF_016126975.1_ASM1612697v1_genomic.fna, strains2/GCF_003429405.1_ASM342940v1_genomic.fna, strains2/GCF_016127775.1_ASM1612777v1_genomic.fna, strains2/GCF_016128215.1_ASM1612821v1_genomic.fna, strains2/GCF_009913955.1_ASM991395v1_genomic.fna, strains2/GCF_001411765.2_ASM141176v2_genomic.fna, strains2/GCF_016028695.1_ASM1602869v1_genomic.fna, strains2/GCF_023277805.1_ASM2327780v1_genomic.fna, strains2/GCF_019614475.1_ASM1961447v1_genomic.fna, strains2/GCF_016726885.1_ASM1672688v1_genomic.fna]
Query = [strains2/GCF_023277765.1_ASM2327776v1_genomic.fna, strains2/GCF_023277785.1_ASM2327778v1_genomic.fna, strains2/GCF_000014505.1_ASM1450v1_genomic.fna, strains2/GCF_009791435.1_ASM979143v1_genomic.fna, strains2/GCF_009930955.1_ASM993095v1_genomic.fna, strains2/GCF_009913995.1_ASM991399v1_genomic.fna, strains2/GCF_002982155.1_ASM298215v1_genomic.fna, strains2/GCF_009914035.1_ASM991403v1_genomic.fna, strains2/GCF_000496265.1_ASM49626v1_genomic.fna, strains2/GCF_009914015.1_ASM991401v1_genomic.fna, strains2/GCF_002202155.1_ASM220215v1_genomic.fna, strains2/GCF_006770865.1_ASM677086v1_genomic.fna, strains2/GCF_007923185.1_ASM792318v1_genomic.fna, strains2/GCF_016126975.1_ASM1612697v1_genomic.fna, strains2/GCF_003429405.1_ASM342940v1_genomic.fna, strains2/GCF_016127775.1_ASM1612777v1_genomic.fna, strains2/GCF_016128215.1_ASM1612821v1_genomic.fna, strains2/GCF_009913955.1_ASM991395v1_genomic.fna, strains2/GCF_001411765.2_ASM141176v2_genomic.fna, strains2/GCF_016028695.1_ASM1602869v1_genomic.fna, strains2/GCF_023277805.1_ASM2327780v1_genomic.fna, strains2/GCF_019614475.1_ASM1961447v1_genomic.fna, strains2/GCF_016726885.1_ASM1672688v1_genomic.fna]
Kmer size = 16
Fragment length = 3000
Threads = 7
ANI output file = output/work/fastani_result
>>>>>>>>>>>>>>>>>>
`
```

The file list is also:

```
strains2/GCF_023277765.1_ASM2327776v1_genomic.fna
strains2/GCF_023277785.1_ASM2327778v1_genomic.fna
strains2/GCF_000014505.1_ASM1450v1_genomic.fna
strains2/GCF_009791435.1_ASM979143v1_genomic.fna
strains2/GCF_009930955.1_ASM993095v1_genomic.fna
strains2/GCF_009913995.1_ASM991399v1_genomic.fna
strains2/GCF_002982155.1_ASM298215v1_genomic.fna
strains2/GCF_009914035.1_ASM991403v1_genomic.fna
strains2/GCF_000496265.1_ASM49626v1_genomic.fna
strains2/GCF_009914015.1_ASM991401v1_genomic.fna
strains2/GCF_002202155.1_ASM220215v1_genomic.fna
strains2/GCF_006770865.1_ASM677086v1_genomic.fna
strains2/GCF_007923185.1_ASM792318v1_genomic.fna
strains2/GCF_016126975.1_ASM1612697v1_genomic.fna
strains2/GCF_003429405.1_ASM342940v1_genomic.fna
strains2/GCF_016127775.1_ASM1612777v1_genomic.fna
strains2/GCF_016128215.1_ASM1612821v1_genomic.fna
strains2/GCF_009913955.1_ASM991395v1_genomic.fna
strains2/GCF_001411765.2_ASM141176v2_genomic.fna
strains2/GCF_016028695.1_ASM1602869v1_genomic.fna
strains2/GCF_023277805.1_ASM2327780v1_genomic.fna
strains2/GCF_019614475.1_ASM1961447v1_genomic.fna
strains2/GCF_016726885.1_ASM1672688v1_genomic.fna
```

**Comment by vebaev** [comment]
Strange thing I noticed, I added one more file from NCBI and it worked, so something is preventing to load mine! Is there some rules about the file name? or naming the fasta seq? its just fasta with 2 contigs, I cannot see any strange thing about it?

**Comment by vebaev** [comment]
PS
I manage to load it, after several attempt of making new input folder  :)
