### ISSUE TITLE
Could you provide information on how you would like this program to be cited

### ISSUE THREAD

**Issue by Unaimend** [moshi4/ANIclustermap#7]

**Comment by moshi4** [comment]
> Could you provide information on how you would like this program to be cited

As shown below, the suggested citation can be found from the repository top page.

![cite_this_repo](https://user-images.githubusercontent.com/41852815/219697479-8c2819de-a8f5-47d7-9fc4-f38e5b5578d9.png)

**Comment by Unaimend** [comment]
Thank you very much. I did not see this.
